spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.95.241.139:3306/java_web_template
    username: beta
    password: password
mybatis:
  mapper-locations: classpath:mapper/*.xml